### PR TITLE
Feat/localservices

### PR DESCRIPTION
**Pull request by deuszex**
Latest commit we managed personally

### CODE REVIEW

**Comment by izolyomi** [comment]
Discussed some minimal cosmethic changes with @deuszex, otherwise it seems to be exactly what we wanted. Maybe the repeated string literals in tests should be constants instead, but I can also live with it as it is.
@wigy-opensource-developer we have to solve 2 things before we can merge this:
 - compatibility: should we simply upgrade all seeds and Titania boxes to the new version or is there a reason for the moment to live with several/different versions?
 - protocol: this PR includes protocol changes in the ProtoBuf file. It should be delegated to the `message-protocol` repository and all other projects using it, e.g. the new crawler and SDK. How to do this properly?

**Comment by wigy-opensource-developer** [comment]
We can complicate things by keeping a backwards compatible interface, or - what I suggest, but we should vote about - simply go forward and update the crawler, the IOP Connect and the Profile Server before rc3 comes out in Titania

**Comment by alcheByte** [comment]
I agree, let's not complicate things with backwards compatibility until we have a reason to :)

**Comment by wigy-opensource-developer** [comment]
So we should push changes to crawler, IoP Connect and Profile Server codebase then. Let's get our hands dirty fast! 😉

**Pull request merged**
